l=int(input('enter lenght '))
b=int(input('enter breadth '))
h=int(input('enter height '))
k=float(l**2+b**2+h**2)
v=float(b**2*h**2/k**(1/2))
x=round(v,3)
print(x)
r=float((3*v/(4*3.14))**(1/3))
s=round(r,3)
print(s)
